### ISSUE TITLE
Can I use this library with Swiftui?

### ISSUE THREAD

**Issue by gandarain** [depoon/URLRequest-cURL#1]
I try to use this library with Swiftui, but I get an error.
This is the error,
<img width="549" alt="Screen Shot 2021-01-16 at 23 07 36" src="https://user-images.githubusercontent.com/27923352/104816762-ab07ae00-584f-11eb-8557-c95390a00343.png">

This is my podfile
````
# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'pos-app' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for pos-app
  pod 'Kingfisher/SwiftUI'
  pod 'ExytePopupView'
  pod 'URLRequest-cURL'
  
  target 'pos-appTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'pos-appUITests' do
    # Pods for testing
  end

end

````

**Comment by depoon** [comment]
did you import
`import URLRequest_cURL`

**Comment by gandarain** [comment]
ohh I am sorry, I use import like this 
````
import URLRequest-cURL
````

I think its solved. Thanks
